# Generated by Django 4.1.7 on 2024-03-29 08:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('roles', models.IntegerField(choices=[(1, 'User'), (2, 'Moderator'), (3, 'Admin')], default=1)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='social_platform\\media\\profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=1000)),
                ('post', models.FileField(upload_to='social_platform\\media\\posts', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'mp4'])])),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_platform.user')),
            ],
        ),
    ]
